Website Sabino Constructor store
server-geeks/WebMine pull request #20
Opened 2022-10-04 00:14 UTC by jackson-roberio

![image](https://user-images.githubusercontent.com/3946126/193707826-518af2d8-e122-434d-9814-9dea1af821ad.png)

2022-10-04 03:54 UTC, mrkc2303 requested changes
I request you to change your repository name in PascalCase
In your case, sabino-constructor -> SabinoConstructor

2022-10-05 20:28 UTC, jackson-roberio commented
> I request you to change your repository name in PascalCase In your case, sabino-constructor -> SabinoConstructor

Hello @mrkc2303 , I have already made the requested changes.

@yellowberard , Could you please review it again?

2022-10-06 07:49 UTC, yellowberard approved these changes

2022-10-06 19:35 UTC, jackson-roberio commented
Hello @yellowberard , I have no access link to the project, the main access is through the index, but any page is accessible without problem.

2022-10-06 19:55 UTC, merged